---
title: Fix a Toilet
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
    description: My thoughts and ideas
    feature_text: 'Welcome to my blog

'
    feature_image: https://picsum.photos/2560/600?image=866
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: pages
  values:
    layout: page
theme: alembic-jekyll-theme
exclude:
- README.md
- Gemfile
- Gemfile.lock
- netlify.toml
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
url: https://mydomain.com
baseurl: ''
description: Easy Toilet Repair
permalink: pretty
<<<<<<< HEAD
logo: "/assets/images/booth-labs-icon-50.gif"

# Pagination
=======
logo: https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c?s=52
>>>>>>> 5d60f65cbe396d8aab32f2b98a4e28620bba46ae
paginate: 5
paginate_path: blog/page:num
navigation_header:
- title: Home
  url: "/"
- title: About
  url: "/about/"
- title: Blog
  url: "/blog/"
navigation_footer:
- title: Back to top
  url: "#top"
