---
title: Fix a Toilet
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
    description: My thoughts and ideas
    feature_text: 'Welcome to my blog

'
    feature_image: "../assets/images/toilet-bowl-water.jpg"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: pages
  values:
    layout: page
theme: alembic-jekyll-theme
exclude:
- README.md
- Gemfile
- Gemfile.lock
- netlify.toml
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
url: https://mydomain.com
baseurl: ''
description: Easy Tiolet Repair
permalink: pretty
logo: "../assets/images/booth-labs-icon-50.gif"
paginate: 5
paginate_path: blog/page:num
navigation_header:
- title: Home
  url: "/"
- title: About
  url: "/about/"
- title: Blog
  url: "/blog/"
navigation_footer:
- title: Back to top
  url: "#top"
